unique_ids:
  assets:
    standard-page.html: IKO24QLUX3WH6BZ4TMKMYS4LK3WSJ7F3
    theme.css: Y36QFFJTNZZ7NJLDZQ43Y4OMW62S6O4X
  forms:
    Form1: VZ3L5P4R5CAUANVHDSPAHZRJZRSL2CC4
  modules: {}
  scripts: {}
  server_modules: {}
